version: '3.9'

services:
  workspace:
    container_name: read_later
    hostname: read_later
    build:
      context: .
      dockerfile: ./infra/docker/python/Dockerfile
      args:
        USER_NAME: ${USER_NAME-myzn}
        GROUP_NAME: ${GROUP_NAME-myzn}
        UID: ${UID-1000}
        GID: ${GID-1000}
        PROJECT_ROOT_DIR: ${PORJECT_ROOT_DIR-.}
        WORKDIR: ${WORKDIR-/opt/work}
    working_dir: ${WORKDIR-/opt/work}
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      - TZ=${TZ-Asia/Tokyo}
    volumes:
      - type: bind
        source: ./src/
        target: ${WORKDIR-/opt/work}
