version: '3.9'

services:
  workspace:
    container_name: ${PROJECT_NAME:-default}-vscode
    hostname: ${PROJECT_NAME:-default}
    build:
      context: ..
      dockerfile: .devcontainer/infra/docker/python/Dockerfile
      args:
        USER_NAME: ${USER_NAME-myzn}
        GROUP_NAME: ${GROUP_NAME-myzn}
        UID: ${UID-1000}
        GID: ${GID-1000}
        PROJECT_DIR: ${PROJECT_DIR-..}
        WORKDIR: ${WORKDIR-/opt/work}
        PYTHONPATH: ${PYTHONPATH-/opt/work}
        POETRY_HOME: ${POETRY_HOME-/opt/poetry}
        PIP_HOME: ${PIP_HOME-/opt/pip}
        SSH_HOME: ${SSH_HOME-/opt/ssh}
    working_dir: ${WORKDIR-/opt/work}
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      - TZ=${TZ-Asia/Tokyo}
      - PYTHONPATH=${PYTHONPATH-/opt/work}
    volumes:
      - type: bind
        source: ../
        target: ${WORKDIR-/opt/work}
